services:
  - type: web
    name: optica-mia-web
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: 1c-2g
    region: oregon
    autoDeployTrigger: commit
    preDeployCommand: /entrypoint.sh migrate
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
      - key: RUN_SEED
        value: "true"
      - key: ADMIN_EMAIL
        sync: false
      - key: POSTGRES_HOST
        fromDatabase:
          name: optica-mia-db
          property: host
      - key: POSTGRES_PORT
        fromDatabase:
          name: optica-mia-db
          property: port
      - key: POSTGRES_USER
        fromDatabase:
          name: optica-mia-db
          property: user
      - key: POSTGRES_DB
        fromDatabase:
          name: optica-mia-db
          property: database
      - key: DATABASE_URL
        fromDatabase:
          name: optica-mia-db
          property: connectionString
      - key: WOMPI_PRIVATE_KEY
        sync: false
      - key: WOMPI_PUBLIC_KEY
        sync: false
      - key: WOMPI_INTEGRITY_SECRET
        sync: false
      - key: ADDI_CLIENT_ID
        sync: false
      - key: ADDI_CLIENT_SECRET
        sync: false
      - key: SISTECREDITO_CLIENT_ID
        sync: false
      - key: SISTECREDITO_CLIENT_SECRET
        sync: false
      - key: GOOGLE_MAPS_API_KEY
        sync: false
      - key: NEXT_PUBLIC_WOMPI_PUBLIC_KEY
        sync: false
      - key: NEXT_PUBLIC_ADDI_CLIENT_ID
        sync: false
      - key: NEXT_PUBLIC_SISTECREDITO_CLIENT_ID
        sync: false

databases:
  - name: optica-mia-db
    plan: 0.5c-1g
    region: oregon
    postgresMajorVersion: "16"
    databaseName: optica_mia
    user: optica