export const TRY_ON_CONFIG = {
  faceLandmarker: {
    modelUrl: "https://storage.googleapis.com/mediapipe-models/face_landmarker/face_landmarker/float16/latest/face_landmarker.task",
    basePath: "/mediapipe/wasm",
    runningMode: "VIDEO" as const,
    minFaceDetectionConfidence: 0.5,
    minFacePresenceConfidence: 0.5,
    minTrackingConfidence: 0.5,
    outputFaceBlendshapes: false,
    maxFaces: 1,
  },
  /** Video constraints for getUserMedia — 640x480 @ 30fps for performance */
  videoConstraints: {
    facingMode: "user" as const,
    width: { ideal: 640, max: 640 },
    height: { ideal: 480, max: 480 },
    frameRate: { ideal: 30, max: 30 },
  },
  /** Target FPS for detection loop */
  targetFps: 30,
  /** Preload URL for model (same as modelUrl, used for <link rel="preload">) */
  modelPreloadUrl: "https://storage.googleapis.com/mediapipe-models/face_landmarker/face_landmarker/float16/latest/face_landmarker.task",
  /** WASM base path for preload */
  wasmPreloadBase: "https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision/wasm",
  faceMeshEngine: {
    leftEyeIndices: [33, 133, 159, 145, 153, 154, 155, 157, 158, 160, 161, 173] as const,
    rightEyeIndices: [362, 263, 386, 374, 380, 381, 382, 384, 385, 387, 388, 390] as const,
    leftIrisIndices: [468, 469, 470, 471, 472] as const,
    rightIrisIndices: [473, 474, 475, 476, 477] as const,
    innerEyeCornerIndices: { left: 133, right: 362 } as const,
    noseBridgeIndices: [6, 197, 195, 5, 168] as const,
    faceOvalIndices: [
      10, 338, 297, 332, 284, 251, 389, 356, 454, 323,
      361, 288, 397, 365, 379, 378, 400, 377, 152, 148,
      176, 149, 150, 136, 172, 58, 132, 93, 234, 127,
      162, 21, 54, 103, 67, 109,
    ] as const,
    earLeftIndex: 234,
    earRightIndex: 454,
    noseTipIndex: 1,
    glassesWidthMultiplier: 2.1,
    verticalOffsetRatio: 0,
    minIrisLandmarks: 478,
  },
  liveEngine: {
    mirrorPreview: true,
    cheekLeftIndex: 127,
    cheekRightIndex: 356,
    glabellaIndex: 6,
    noseBridgeIndex: 168,
    noseTipIndex: 1,
    noseBaseIndex: 4,
    noseBridgeLowerIndex: 5,
  },
  smoothing: {
    positionAlpha: 0.35,
    angleAlpha: 0.22,
    scaleAlpha: 0.3,
    deadZonePx: 0.8,
  },
  clamps: {
    maxYawDeg: 25,
    maxPitchDeg: 15,
  },
  perspectivePx: 900,
  referenceIpdMm: 63,
  baseFrameScale: 2.16,
  cpuThrottleDivisor: 2,
  faceLostGraceMs: 800,
  canvas: {
    maxWidth: 800,
  },
  upload: {
    maxSizeBytes: 10 * 1024 * 1024,
    acceptedTypes: ["image/jpeg", "image/png", "image/webp"],
  },
  overlay: {
    storageKey: "optica-mia-try-on",
  },
  temple: {
    referenceIpdPx: 150,
    baseLengthPx: 180,
    baseWidthPx: 30,
    minOpacity: 0.15,
    maxOpacity: 0.95,
    templeMarginFactor: 1.1,
  },
  timeouts: {
    modelLoad: 30000,
    cameraPermission: 15000,
    videoReady: 10000,
    videoPlay: 10000,
  },
  messages: {
    noFace: "No pudimos detectar tu rostro. Intenta con una foto frontal y bien iluminada, sin tapar tu cara.",
    multipleFaces: "Solo debe aparecer una persona en la foto.",
    modelError: "No se pudo cargar el modelo de detección facial. Verifica tu conexión.",
    modelTimeout: "La carga del modelo está tardando demasiado. Verifica tu conexión e inténtalo de nuevo.",
    detectionError: "Ocurrió un error al procesar la imagen. Intenta con otra foto.",
    uploadError: "La imagen no es válida. Usa JPG, PNG o WEBP (máx 10 MB).",
    imageNotReady: "La imagen aún no está lista para analizarse. Intenta nuevamente.",
    cameraDenied: "No autorizaste el acceso a la cámara. Habilítala en los permisos del navegador e inténtalo de nuevo.",
    cameraNotFound: "No encontramos una cámara conectada a tu dispositivo.",
    cameraTimeout: "La cámara tardó demasiado en responder. Verifica que no esté en uso por otra aplicación.",
    modelErrorLive: "No se pudo cargar el motor de detección facial. Verifica tu conexión e inténtalo de nuevo.",
    noFaceLive: "No detectamos tu rostro. Ubícate de frente a la cámara con buena iluminación.",
    cameraInUse: "La cámara está en uso por otra aplicación. Cierra otras apps e intenta de nuevo.",
    cameraConstraint: "Tu cámara no soporta la resolución requerida (640x480).",
  },
} as const;

export type TryOnStatus = "idle" | "loading-model" | "starting-camera" | "running" | "error";